const form = {
  "item": {
    "num_iid": "",
    "id": "",
    "productId": "",
    "categoryId": "",
    "venderId": "",
    "title": "",
    "options": [],
    "attr": [],
    "requireDetailData": [],
    "detailImage": [],
    "desc_short": "",
    "price": "",
    "total_price": "",
    "suggestive_price": "",
    "original_price": "",
    "nick": "",
    "num": 0,
    "detail_url": "",
    "pic_url": "",
    "brand": "",
    "manufacturer": "",
    "modelName": "",
    "brandId": "",
    "rootCatId": "",
    "cid": "",
    "nid": "",
    "desc": "",
    "item_imgs": [],
    "item_weight": "",
    "post_fee": 0,
    "freight": "",
    "express_fee": null,
    "ems_fee": "",
    "shipping_to": "",
    "video": "",
    "sample_id": "",
    "props_name": "",
    "prop_imgs": {
      "prop_img": []
    },
    "props_imgs": {},
    "property_alias": "",
    "props": [],
    "total_sold": "",
    "skus": {
      "sku": []
    },
    "seller_id": "",
    "sales": 0,
    "shop_id": "",
    "props_list": {},
    "seller_info": {},
    "tmall": false,
    "error": "",
    "fav_count": null,
    "fans_count": "",
    "location": "",
    "data_from": "",
    "has_discount": "",
    "is_promotion": "",
    "promo_type": null,
    "props_img": {},
    "rate_grade": "",
    "desc_img": [],
    "desc_text": [],
    "shop_item": [],
    "relate_items": [],
    "shopName": "",
    "url": ""
  }
}

export {
  form
}